### ISSUE TITLE
Half the recipes in a folder are moved when dragged-and-dropped into another folder

### ISSUE THREAD

**Issue by cgiacofei** [Brewtarget/brewtarget#195]
I am experiencing some strange behavior in version 2.3.0.

When a folder containing recipes is dragged inside another folder only some of the recipes in the folder are moved. 

At first it appears as though the recipes not moved have disappeared, but after saving and closing Brewtarget the recipes will be in there original location when the software is reopened.

I attached a couple screen shots showing what I am talking about.

![recipes](https://cloud.githubusercontent.com/assets/8628544/13116941/ebbc318a-d56b-11e5-8538-63cbc4c52ee4.png)

**Comment by mikfire** [comment]
It is predictable behavior. You will move n/2 or (n+1)/2 items, depending on if there are an even or odd number of items in the folder you are moving. Subfolders in the folder being moved will make things less predictable.

The work around is mildly annoying. Create the target subfolder(s) and move just the recipes into place. 

I will get a patch together later, but I really need to consider what happens when moving folders with multiple subfolders.

**Comment by mikfire** [comment]
Should be closed w/ pul request 197

**Comment by rocketman768** [comment]
Closed in #200.
