### ISSUE TITLE
Crash when importing .xml-file

### ISSUE THREAD

**Issue by OiPenguin** [Brewtarget/brewtarget#280]
Brewtarget crashes instantly when attempting to import a beer .xml-recipe downloaded from Brewtoad. I tried this file: https://www.brewtoad.com/recipes/brooklyn-pennant-ale-55-clone-brooklyn-brewery.xml

My system: Ubuntu 16.04, Brewtarget v 2.3.0.

**Comment by OiPenguin** [comment]
An update. Importing a file from brewgr.com does not cause a crash, however it does not import properly and I get the following error message: "The import contains invalid beerXML. It has been imported, but please make certain it makes sense." Unfortunately, it doesn't really make sense.

I also tried importing a beerXML from brewersfriend.com. The import appears to be working well. No dialogue box signalling error, however in the left hand corner of brewtarget it says: ERROR: BeerXMLElement::getBool: true is not a boolean value. Line 159. More importantly, the calculatins made by brewersfriend.com vs Brewtarget are very different. Se this file for a comparison: https://www.dropbox.com/s/ek8q73egoe69jek/brewersfriendVSbrewtarget.png?dl=0

**Comment by mikfire** [comment]
This is a brewtoad problem. They generate bad beerXML. I've opened a ticket
with them, but it was closed with a "it works with beersmith".

BeerXML as a specification sucks. All of the awful of XML, with no
validation possible. So we can't even validate it.

There are a number of fixes going into v2.4 that should prevent us from
dumping core on bad input.

Mik

An update. Importing a file from brewgr.com does not cause a crash, however
it does not import properly and I get the following error message: "The
import contains invalid beerXML. It has been imported, but please make
certain it makes sense." Unfortunately, it doesn't really make sense.

I also tried importing a beerXML from brewersfriend.com. The import appears
to be working well. No dialogue box signalling error, however in the left
hand corner of brewtarget it says: ERROR: BeerXMLElement::getBool: true is
not a boolean value. Line 159. More importantly, the calculatins made by
brewersfriend.com vs Brewtarget are very different. Se this file for a
comparison:
https://www.dropbox.com/s/ek8q73egoe69jek/brewersfriendVSbrewtarget.png?dl=0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Brewtarget/brewtarget/issues/280#issuecomment-226768103>,
or mute the thread
<https://github.com/notifications/unsubscribe/AKxgF6iI_j_2Jf8xXkrsXBUfiXq6P6i6ks5qMqBvgaJpZM4I4U95>
.

**Comment by rocketman768** [comment]
Can you export the .xml file or post a screenshot of your equipment profile (you can drag and drop on github)? Manual calculation assuming 6.5 gal boil size shows the OG should be 1.050.

**Comment by OiPenguin** [comment]
![equipment-profil](https://cloud.githubusercontent.com/assets/858969/16361994/f87aecd0-3ba1-11e6-9bef-98e05e795833.png)

**Comment by pricelessbrewing** [comment]
Confirmed issue with a recipe from brewtoad and brewgr. I do suspect this is an issue on their ends though. 

Hops did not import correctly, I only got the first hop addition. 

Not sure if fermentables went through correctly due to differences in units for potential/yields. Fermentable additions usage "mashed/steeped" did not carry over correctly. 

After those were adjusted by hand, OG, IBUs etc lined up about as well as can be expected given differences in formulas for IBUS etc. 

Did not do analysis on brewtoards data as I've heard that they produce bad data from multiple sources. 

Tested against beersmith and brewersfriend, worked fine no error message or differences.

**Comment by matty0ung** [comment]
I'm hoping the https://github.com/Brewtarget/brewtarget/pull/515 patch, once reviewed by @mikfire, will address this and similar issues by making XML import a lot more robust.  If something isn't valid BeerXML, that patch means the software should tell you which line of the input file is the culprit instead of, say, just crashing  :smile:.  I tried to test the files for which this ticket was originally raised, but the links seem no longer valid.  If someone still has those XML files and wants to add them directly to this ticket, then I can tell you what output the new code gives with them.
