### ISSUE TITLE
Database wiped on Mac OS X 10.12 due to logout

### ISSUE THREAD

**Issue by xor-gate** [Brewtarget/brewtarget#333]
I'm unable to recover my database/recipes as for some reason it has been killed/unproper quit and now my brews are gone. I'm running brewtarget v.2.3.0. This is probably due to forced kill and the window "do you want to save changes" is then skipped. I tried to dig up the sqlite DB under `.config` without luck. I known brewtarget > v2.3.0 has a auto-backup feature, but not in v2.3.0.
 
:-(

**Comment by xor-gate** [comment]
This is probably due to (System Preferences -> Security):

<img width="679" alt="screen shot 2016-11-19 at 20 18 17" src="https://cloud.githubusercontent.com/assets/1050166/20457869/57d5e070-ae95-11e6-82e7-fba70a561036.png">

**Comment by creativecoder** [comment]
I've also had my database wiped out on macOS. In my case, I made some recipe changes that I didn't want to save. When I closed the program and said "No" to saving changes, it wiped out all recipe data I had ever entered in the program.

## Steps to Reproduce

1. Open brewtarget. Past recipes and batches appear when you load the program.
2. Make a change to a recipe that you don't want to save.
3. Quit brewtarget.
4. Select "No" when asked if you want to save changes.
5. Wait for brewtarget to finish quitting, then open it again.

## Expected result
You see all your recipes and information, except for the last change you didn't want to save.

## Actual result
Anything you've added since you started using the program is gone.

**Comment by xor-gate** [comment]
I stopped using brewtarget and now store all my recipes in an spreadsheet which will always work. To bad.

**Comment by pricelessbrewing** [comment]
Losing recipes is a pretty important issue, so setting this to bug/high priority. 

Those with macs, can you please create backups of your database file, then try to reproduce the error in 2.3 and 2.4?

**Comment by creativecoder** [comment]
I retried the steps I listed previously

> 1. Open brewtarget. Past recipes and batches appear when you load the program.
> 1. Make a change to a recipe that you don't want to save.
> 1. Quit brewtarget.
> 1. Select "No" when asked if you want to save changes.
> 1. Wait for brewtarget to finish quitting, then open it again.


Looks like the issue is fixed. I am now getting the expected result: my changes are not saved but all previous data is still there.

**Comment by pricelessbrewing** [comment]
Thanks @creativecoder I'm going to leave this open for a little while longer. Would like multiple confirmations against 2.3 and dev branch (pending 2.4 release) since it looked like there was multiple issues with the mac build.

**Comment by mattiasmaahl** [comment]
This was resolved 3 years ago, will close now.
