### ISSUE TITLE
Mash wizard does not adjust sparge water temperature for changes in mash temperature

### ISSUE THREAD

**Issue by gkornelson** [Brewtarget/brewtarget#357]
Using brewtarget 2.3.0 on Ubuntu:

I create a mash-in step, set a target temperature, and then run the mash wizard and it spits out strike water volume and temperature for that target, and a volume and temperature for the batch sparge step.

If I change the target temperature of the mash and re-run the mash wizard, it adjusts the initial strike water temperature, however does not change anything in the batch sparge step. I get the same behavior if I remove all mash steps and start over, using a different mash target temp. It will spit out the same batch sparge volume and water temperature no matter what temperature my mash is at.

**Comment by gkornelson** [comment]
This bug is also present using Windows, version 2.3.0. Seems to work the only the first time the mash is setup, even after restarting brewtarget.

**Comment by kapinga** [comment]
I was able to confirm this. The problem only seems to exist when there is exactly one extraction step in the mash:
![image](https://cloud.githubusercontent.com/assets/1765623/23802673/00060c32-0582-11e7-882f-418a4e9bff8f.png)
![image](https://cloud.githubusercontent.com/assets/1765623/23802683/08635d30-0582-11e7-88d7-99bbefe291db.png)
The temperature of the sparge water is calculated a bit differently than regular infusions, but it certainly shouldn't be the case that a mash at 50 C and a mash at 65 C need the same volume and temperature of sparge water to hit 74 C.

I'll dig into the Mash Wiz logic and see what's going on. When there's more than one extraction step the problem seems to go away though.

For now, use the Mash Designer, which should not suffer from this problem.

**Comment by kapinga** [comment]
So I figured this out for version 2.3.0/2.3.1. There was an off-by-one error in the MashWizard code that caused it to always use the default MashStep temperature (67 C) instead of the actual final temperature.

It's a one-line fix for version 2.3.1. I'm now checking into whether this is a problem for the development branch (there's been a big rewrite of MashDesigner in the interim.

**Comment by kapinga** [comment]
I just looked at the current develop branch, and it does not suffer from this bug. The sparge steps are created after determining the last mash step's temperature, so the last mash step correctly provides the mash temperature.

**Comment by pricelessbrewing** [comment]
Also confirmed on latest dev build. Closing issue.
