### ISSUE TITLE
FG calculation does not take into account unfermentable ingredients (example: Lactose)

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#358]
Example, adding 1 lb of lactose to a 5.5 gallon batch should raise the FG by approximately 6.37 gravity points (35/5.5).

However in brewtarget, it's treated the same as any other sugar source, and increases the fg by 2 points.

**Comment by kapinga** [comment]
Right now, Brewtarget's fermentable sugar calculations have a special case for "Milk Sugar (Lactose)" that are supposed to process the sugar as non-fermentable. There's no property in BeerXML that corresponds to unfermentable sugar, which is why (I assume) that it's included as a hard-coded special case (see [recipe.cpp](https://github.com/Brewtarget/brewtarget/blob/stable/2.3.0/src/recipe.cpp#L450)). We should probably think about a better way of handling this, but for now make sure you name your added lactose by that special-cased name exactly.

Quickly checking, I can confirm that adding 1 lb of "Milk Sugar (Lactose)" to a recipe increases the OG by ~5 points, but only increases the FG by ~1-2 points. I'm poking around now to see why the non-fermentable sugar content is getting ignored.
