### ISSUE TITLE
Cannot delete style

### ISSUE THREAD

**Issue by dpettersson** [Brewtarget/brewtarget#371]
Mike Morris wrote:

For reasons of (legacy database?) I have FOUR styles all called "English IPA". I'd like to delete 3 of them, but cannot. Tried renaming some of them to "Enlish IPA-2", "English IPA-3" etc. and then deleting those, but,... no go. Stuck with them.

------------

I have asked for more information about Brewtarget version, OS and also a copy of the database to test with.

**Comment by mikro2nd** [comment]
Copy of database at https://www.dropbox.com/s/uwrybc1vvs2t9j3/database.sqlite.gz (because for $REASONS github won't/can't accept zip files from linux zip, nor gz nor bzip ;P)

**Comment by dpettersson** [comment]
I cant get the data base you sent me to work.
Brewtarget only loads the default styles.

Can you send it again?     send at moc.liamg(ta)18nosttep   :)

2017-07-06 15:24 GMT+02:00 Mike <notifications@github.com>:

**Comment by pricelessbrewing** [comment]
@dpettersson did you ever get a copy to test? 

@mikro2nd  Is this still an issue? I'm able to delete styles just fine in 2.3 and 2.4.

**Comment by mikro2nd** [comment]
Still appears to be an issue for me (BT 2.3.0). I am trying to delete the renamed styles from the **styles tab** (select style from list, right-click, select "Delete", "Yes" in confirm dialogue) and **not** from the Styles Editor. When accessing the styles via the Styles Editor window, no duplicates show up.

I *think* I sent the db again, but it's a long time ago... let me know if you want me to send again.

If someone says to me, "You've got a fubarred database. Start afresh." that is probably OK for me (provided I can figure out how to import all my recipes without the suspect styles data) so this is probably not the highest priority issue in anyone's life. Reported mainly because in my own experience these things can sometimes be a flag for other dbintegrity/data-validation related bugs.

And for silly GitHub reasons I am unable to attach a screen-grab...??

**Comment by pricelessbrewing** [comment]
Testing in 2.3. After restoring db to your file, and merging my db with your db I get the same message. Unable to delete any style entry, or the entire style folder.

"WARNING: deleteSelected:: unknown type: 7"

Testing in 2.4 

Works fine after restoring db to your file, or merging db together. 

Recommendation: If you're unable to build a new one, I would recommend opening the sq.lite file with an appropriate editor, and deleting all the style entries by hand. Then you can try merging the db with one that has a healthy style table.

**Comment by matty0ung** [comment]
If this is fixed in 2.4, I think we should just close this ticket.
Please re-open the ticket if I've misunderstood.
