### ISSUE TITLE
2.4 creating recipe crashes brewtarget

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#419]
Doesn't happen 100% of the time, but crashes reliably when

On the left, switch from recipes to ingredients. Select one.

File>new recipe>put a name in>hit OK. 

Should crash. Repeated ~10x with hops, fermentables, and yeast. Works fine when you're in the recipe tap on the left.

**Comment by pricelessbrewing** [comment]
Not really. Built from latest dev brach at the time. Will try it again. 

Note on Windows 10.

**Comment by dpettersson** [comment]
I tested with 2.4 in linux

Den 23 sep. 2018 20:31 skrev "Mark Price" <notifications@github.com>:

Not really. Built from latest dev brach at the time. Will try it again.

Note on Windows 10.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Brewtarget/brewtarget/issues/419#issuecomment-423837169>,
or mute the thread

**Comment by pricelessbrewing** [comment]
No longer getting this issue on latest build. Closing issue.
