### ISSUE TITLE
Import bsmx equipment profiles

### ISSUE THREAD

**Issue by padraic7a** [Brewtarget/brewtarget#445]
It would be great to be able to import Beersmith equipment profiles.

**Comment by dpettersson** [comment]
Do you have any examples?
It is easier for us to figure out how it works if we have an example.

**Comment by padraic7a** [comment]
Sure, I should have thought of that. Coobra is an all in one brewing system a la Grainfather. (It is also available under other names such as the Bulldog Brewer). 
They make a Beersmith .bsmx equipment profile available on this page: https://www.olkompaniet.se/coobra-cb3
I am attaching an unzipped file here for convenience, though I had to change teh exension from.bsmx to .txt
[Coobra CB25 1,8 kw.txt](https://github.com/Brewtarget/brewtarget/files/3231144/Coobra.CB25.1.8.kw.txt)

**Comment by dbeniciorj** [comment]
Hi guys, importing a bsmx profile to the database would be very nice because we would import some regional ingredients profiles too, like national malts and hops, instead of creating items one by one. It seems Beersmith uses these files to improve customization.
I'm looking forward to see this update cause BT is incredible and I'd like to use it more.
Here I have another example, renamed as extension txt.
[Maltes_BR_Craft.bsmx.txt](https://github.com/Brewtarget/brewtarget/files/5507487/Maltes_BR_Craft.bsmx.txt)

**Comment by mikfire** [comment]
BSMX is beersmith's custom format. It can and will change between versions as beersmith makes changes to it. Every time beersmith makes a change, we then have to dig into the code, figure out what changed and fix it.

This seems like we are making work for ourselves, and creating problem tickets over the long haul. It makes me very hesitant to implement the support.

**Comment by dbeniciorj** [comment]
Hello @mikfire , i agree 100% with you. But this feature is one of the best features of beersmith, wich is the "market" standard, and many vendors  use it to export equipments and ingredients profiles to that "standard" software, what makes it more and more popular... I can't see a way out of this path. And possibly having a utility like this would popularize Brewtarget even more, because it makes easier to create a recipe with real items instead of making many substitutions.

A blind shot, if I can suggest it, would be to adopt an open standard for this type of customization in Brewtarget (or maybe even create an open standard if it doesn't exist, since we use open source here!). Therefore, the job of converting bsmx to this suggested open standard would be part of brewtarget itself, **or not!** (it would be part of another project). Anyway, the cornerstone of this idea would be first having a way to import any standardized profile into Brewtarget database.

PS: I would help it here but I'm not fluent in C/C++ to propose a branch with this data importing feature. Although I would help with Python or another script to convert bsmx to brewtarget standard!!

**Comment by matty0ung** [comment]
Having a way to import equipment profiles would be a good feature (and was something I missed when I started using BrewTarget).  If the current de facto standard for such profiles is the BSMX XML format then we could look at that as at least a starting point - not least as it's XML-based and there are lots of existing real-world files out there for us to parse.  I'm happy to at least take a look at this once I've finished Undo/Redo.

In parallel, working to create/extend a standard open format for these things would also be a good initiative.  Maybe even the BeerSmith folks would be open to this, seeing as Brad Smith contributed to http://www.beerxml.com.

**Comment by mikfire** [comment]
I'm a little confused. 

We have a way to exchange profiles. It is called BeerXML. The entire point of BeerXML is to allow different software to exchange these profiles without having to understand each other's formats. We should no more have to understand beersmith's proprietary format than beersmith should have to understand our database schema.

If beersmith no longer supports BeerXML, that is beersmith's bug and not one we should have to fix.

I wish I could be open minded here, but I find I cannot. brewtarget is opensource. Reverse engineering a closed source format is wrong. It enables one player (beersmith) to decide what is and what isn't appropriate for homebrewing software. I am dead set against that.

If beersmith wants to publish their format as a new specification, I would be willing to consider it. But I am not willing to reverse engineer their format.

If I haven't been clear enough. I am not willing and likely will not approve any PR for supporting this format without sufficient documentation to make it an open source. If the other maintainers chose to do so, I will not reverse the commit.

**Comment by padraic7a** [comment]
I think that makes sense.

**Comment by mattiasmaahl** [comment]
I side with Mik on this one, Beersmith .bsmx format is a proprietary format that is not intended to me used in other softwares for importing/exporting profiles/equipment or recipies, we have BeerXML which works the same way but for all brewing softwares, and there is also work being done to create the beerJSON format, both open standards that will be possible to maintain over a foreseeable future.

**Comment by matty0ung** [comment]
Ah, didn't know BeerXML could do equipment profiles - and couldn't see equipment profile import in the BT UI.
Yes, if we can already represent profiles in BeerXML, then I agree that should be our default format.

Equally I think there is an argument for being able to _read_ from other file formats in certain circumstances - either directly or via a free-standing conversion tool - eg if manufacturers only publish their equipment profiles in one format.  (It's annoying if this requires a bit of reverse-engineering of such formats, but it's hardly unprecedented for open-source projects to have to do this - see eg LibreOffice being able to read MS Office proprietary file formats.)

**Comment by mattiasmaahl** [comment]
I do agree with you that there cases where Open Source read from proprietary file formats, although the Microsoft file formats are an "open" standard, where the most part of the standard is open and free and other parts are Licensed and subject to a fee.
But that aside, I do not disagree with a third party tool to convert from other formats, i.e. bsmx, to BeerXml before importing to BT, but I find it not likely that we'll implement the tool into BT in the near future.

**Comment by matty0ung** [comment]
Maybe we should accept the offer of @dbeniciorj to write such a freestanding tool in Python? :)

**Comment by jt196** [comment]
Currently doing a bit of work with Beersmith xml and bsmx files. Happy to have a look into customising a parser for the equipment profiles. I've already been able to import ingredients (hop, malt, water, yeast, misc) into an SQLite database with etree and Pandas, don't see why equipment should be such a big step. 

I have found etree doesn't play well with non-html characters, meaning the bsmx recipe file I was trying to parse didn't import. It may be the xml files don't have the same encoding. Will look into this later today.

**Comment by matty0ung** [comment]
I'm going to close this as I don't see us doing the work inside Brewtarget to reverse-engineer the BSMX file format.  (I remember having a look and thinking it's doable but non-trivial.  Feels like getting BeerJSON working is a bigger priority.)

(Obviously if and when someone gets a chance to make a free-standing utility that converts Beersmith proprietary file format to either BeerXML or BeerJSON, that would be great and we'd be happy to hear about it.)
