### ISSUE TITLE
CI/CD automated builds

### ISSUE THREAD

**Issue by cgspeck** [Brewtarget/brewtarget#456]
It would be good to have CI/CD and automated binary builds on PRs and merges.

I suggest the goals of this would be to:
1) automatically build binaries for popular linux targets ~~supported by Docker~~
2) automatically run the tests
3) automatically publish ~~(as [Github releases](https://github.com/cgspeck/brewtarget/releases))~~ passing binaries
4) publish a Guacgui docker images [with Brewtarget develop installed](https://hub.docker.com/r/cgspeck/brewtarget-guacgui)

It could in the future be extended to create:
a) OS specific dev releases (e.g. update PPA for Ubuntu, AUR for Arch)
b) Windows builds (it would be amazing to be able to recommend this to my non-tech friends).

I've created a similar workflow using TravisCI on my fork and offer it as [an example](https://travis-ci.com/github/cgspeck/brewtarget/builds/136039274). 

I will have some spare time coming up soon and will be happy to work on this in a few weeks.

**Comment by xzfantom** [comment]
Why this issue was closed? I think the idea of CI/CD is very good and was working in same direction. And as far as I can see @cgspeck already made most of it.

**Comment by matty0ung** [comment]
Looks like a typo - AFAICT intent was to close https://github.com/Brewtarget/brewtarget/issues/455 rather than https://github.com/Brewtarget/brewtarget/issues/456.  Reopening.

**Comment by cgspeck** [comment]
I have opened a draft PR with my working build, see #523 

What specific version of QT we should be using (I chose 5.14.2, it needs to be >= 5.10 for the test suite)?

Should we explicitly list Debian dependencies or rely on `CPACK_DEBIAN_PACKAGE_SHLIBDEPS`? (see [this patch](https://github.com/Brewtarget/brewtarget/pull/523/files#diff-1af3ff0c718f9f5b8b422a01a148a5761adb2f7dcb66a7e0d38114a1b98a9bf1))

**Comment by xzfantom** [comment]
About minimal QT5 version we have issue #521 and there is no final decision yet.

I was working on the same question here [develop.yml](https://github.com/xzfantom/brewtarget/blob/feature-cpack-lintian-check/.github/workflows/develop.yml). And some my thoughts are here:

I used MSYS2 because it has it's package manager and library xalan-c, that can be useful if PR #515 get merged.

Also I don't like the idea to add vendor binaries - I downloaded them in [action](https://github.com/xzfantom/brewtarget/blob/00f6f3103fc36432e8827654d9b0f188b771a2e2/.github/workflows/develop.yml#L39).

And if you add **umask 022** and parameter for cmake **-DEXEC_PREFIX=/usr** ([see](https://github.com/xzfantom/brewtarget/blob/00f6f3103fc36432e8827654d9b0f188b771a2e2/.github/workflows/develop.yml#L105)) it will build better deb package if test with lintian, some discussion #489 .

**Comment by xzfantom** [comment]
P.S. if it's CI\CD on base of Github Actions, we can get rid of Travis (.travis.yml) and change Build Status in README.markdown

**Comment by cgspeck** [comment]
@xzfantom thank you for the feedback. 

I attempted to use your action template for the Windows build but the installed app complained of missing the following libraries: `zlib1.dll, libicuin68.dll, libicuuc68.dll, libpcre2-16-0.dll,  zlib1.dll, libpng16-16.dll, libharfbuzz-0.dll`, so I reverted it and the artefact is installable and runnable in Windows.

I have also:

* linux: added umask
* linux: added lintian and rpmlint
* windows: removed vendored libs, now download and install Locate & Log during build;
* replace build status badges, removed `.travis.yml`;
* updated README;

The PR now satisfies goals 1-3 of this issue. It does not address other complex/long standing issues but it does provide working installers and binaries and provides updated builds of Brewtarget to non-technical users.

**Comment by xzfantom** [comment]
> I attempted to use your action template for the Windows build but the installed app complained of missing the following libraries: `zlib1.dll, libicuin68.dll, libicuuc68.dll, libpcre2-16-0.dll, zlib1.dll, libpng16-16.dll, libharfbuzz-0.dll`, so I reverted it and the artefact is installable and runnable in Windows.

I found that MSYS2 project build qt5 with shared libs. They have qt5-static package, too, so I want to check if it'll work for our needs. The reason I used MSYS2 and not regular MinGW is that if PR #515 will be merged we need to obtain Xerces-C and Xalan-C libraries. For the second one building in MinGW is broken for now, but MSYS2 patched it. Only this PR is opened for 3 months and nobody knows if it'll be merged or not.

**Comment by mattiasmaahl** [comment]
@xzfantom As the PR #515 is merged now, do you think that you have the time to make the necessary adjustments to the CI/CD to include the Xerces and Xalan libs?
If not, kindly let me know and I'll look into it.

**Comment by xzfantom** [comment]
Yes, of course. There is no problem with Xerces.
There is no working Xalan-C library for MinGW yet, but developers are promising to make it in next version. So guys from MSYS2 and vcpkg made some patches for it to work.

I've got working build for windows using MSYS2. The problem (or feature) with it is that they use *nix philosophy and use package management system and shared libs. Program, compiled in this environment need more libs as @cgspeck mention. Not really a big problem - the size of program is pretty much the same. Only need to introduce some new code in CMakeLists.txt for auto dependency resolution.
Or we can use patches from MSYS2 project and build Xalan) Like temporary workaround, but nobody knows when new version of Xalan will be out.

Second way is to use VS and vcpkg instead of MinGW and MSYS2, but I'm not really familiar with it.

**Comment by mattiasmaahl** [comment]
@xzfantom So I have been tinkering with this for a while and my conclusion is that you're pretty much tied down to MSYS/MinGW on windows for now as vcpkg shipps Xalan-C 1.11 rather than Xalan-C 1.12, and Xalan-C 1.11 does not build with Brewtarget due to some undefined references. For now I have not been able to figure out how to make brewtarget work with VS. still working on it though.

**Comment by xzfantom** [comment]
Yeah, right. I don't have VS so I can't test it. 
I use VSC + MSYS2 in windows and VSC through SSH and native packages in linux. 
I have plans to add CI build with VS and vcpkg, but due to lack of experience didn't start it yet - it's hard to debug GitHub Actions because you can't test it locally and should push changes to server and watch how it's doing.
One of the solution is to add issue to vcpkg with request to bump Xalan-C version or build it from source for now.

**Comment by mattiasmaahl** [comment]
Yes, I agree with you.
For the moment VS-build is broken and you are forced to use MinGW/MSYS. I'm still hopeful to find a solution on how to make it work. 
I'll make the request to vcokg-project to bump the version, But I'm holding my breath it will happen any time soon. last I checked there were around 1300 issues and more than 200 PRs on that project. 🤷‍♂️

**Comment by xzfantom** [comment]
There is interesting situation - xalan-c build is broken for MinGW, so MSYS2 uses some patches to make it work. It can be built in VS, but outdated in vcpkg repos )

**Comment by mattiasmaahl** [comment]
figured out how to fix the Visual Studio Issues. And updated the Wiki to include how to install the libraries with vcpkg for Visual Studio and also changed the 32-bit instructions for MSYS to 64bit. I hope you don't mind @xzfantom? ☺

**Comment by xzfantom** [comment]
> changed the 32-bit instructions for MSYS to 64bit

There is only one trouble - NSIS plugins are 32bit, so you can't create installer if you build in 64bit environment. For development purposes there is no difference.

**Comment by xzfantom** [comment]
> EDIT: I aslo saw that the VCPKG repo now has a PR for the 1.12 bump in versions for Xalan-C. so once that is accepted into their standard repo it's good to go!

They finally merged this PR. We can add one more option to CI/CD and build Bt with vcpkg.

**Comment by mattiasmaahl** [comment]
Yes, I got the notice today that they merged it. I'm gonna try to run some builds next week on those libraries.

**Comment by mattiasmaahl** [comment]
CI/CD is up and running, I'll close this ticket.
