### ISSUE TITLE
Crashing after update to Mac OS  Catalina

### ISSUE THREAD

**Issue by ippyfil** [Brewtarget/brewtarget#460]
After updating to Mac OS Catalina, my brewtrget just broke. Apparently I lost all the data I had and cannot use it. When I open it, I receive the multiple databases found, and after open it (clicking restore or rollback) the program crashes when I try to choose the equipement (or anything else actually). I have uploaded the crash report
[brewtarget_crash.txt](https://github.com/Brewtarget/brewtarget/files/4592343/brewtarget_crash.txt)

**Comment by matty0ung** [comment]
Do you know which version of Brewtarget are you running?
Also, could you upload the database file you were using?

**Comment by matty0ung** [comment]
@ippyfil From looking at your crash file, it seems the program is opening the Equipment Editor window and trying to get the equipment for the current recipe.  However, for some reason there isn't any equipment assigned to the current recipe, and the version of the code you are running does not handle that gracefully - ie it crashes!

This is, however, fixed in the latest versions of the code (the 2.4.0 release candidate and the current development branch), in that, if you try to edit the equipment of a recipe that doesn't have equipment assigned to it, you'll get an error message that says "No equipment: You must select or define an equipment profile first."

Please do add another comment here if this doesn't resolve your issue.

**Comment by matty0ung** [comment]
Closing since fixed in the current version of the software (3.0.0).
