### ISSUE TITLE
Cannot Start Brewtarget

### ISSUE THREAD

**Issue by 90percentbrewer** [Brewtarget/brewtarget#470]
I replaced my drive on my mac and moved the apps from the old drive to the new one.  I am now getting this message 
/Volumes/Macintosh HD/Users/xxxxxx/.config/brewtarget" cannot be read.

where xxxx is my username.  How can I do a clean uninstall or how do I point this to the new volume

The "Macintosh HD" was the name of my old disk when I replaced it I gave the new disk a new name

**Comment by dpettersson** [comment]
HI, My guess is that there is some environmental variable left that points to that directory.

BrewTarget uses the users home directory variable to find the config and the databases. Since you have changed the disc it is possible that some of the paths in the environmental setup points to the old directory. 

you can print the current variables by running "printenv" in a terminal. If the output is really long use grep to search for your username.

**Comment by mikfire** [comment]
To be really pedantic about this, the code first looks for an environmental variable called XDG_CONFIG_HOME. If that isn't set, we look for an environmental variable called HOME. If we can't find that, we use /. 

My guess is that you probably have the HOME variable set and it is pointing to the old location.

**Comment by 90percentbrewer** [comment]
> To be really pedantic about this, the code first looks for an environmental variable called XDG_CONFIG_HOME. If that isn't set, we look for an environmental variable called HOME. If we can't find that, we use /.
> 
> My guess is that you probably have the HOME variable set and it is pointing to the old location.

Thanks. Where would I find these variables at?

**Comment by mikfire** [comment]
Well, if you were on any one of a number of *nix variants, I could probably answer that.

On a Mac? I think if you were to use your preferred search engine and ask for "mac set homedir", you might get enough information to help out.

**Comment by 90percentbrewer** [comment]
So my HOME variable is pointed to my new drive....Checked by using echo $HOME  and also went to the GUI to see where the HOME directory is, both are showing the new drive name but BrewTarget is trying to point to my old directory

**Comment by 90percentbrewer** [comment]
echo $HOME
/Volumes/Macintosh SSD2/Users/cXXXXh

message while trying to launch brew target

/Volumes/Macintosh HD/Users/cXXXXh/.config/brewtarget" cannot be read

**Comment by 90percentbrewer** [comment]
echo $HOME
/Volumes/Macintosh SSD2/Users/cXXXXh

message while trying to launch brew target

/Volumes/Macintosh HD/Users/cXXXXh/.config/brewtarget" cannot be read

**Comment by matty0ung** [comment]
Don't know if it will help diagnose this specific bug, but might not hurt to add some logging of whether we are using XDG_CONFIG_HOME or HOME.  Otherwise can be hard to be certain which environment variables are set if you're starting an app from the GUI rather than the command line.  Have added https://github.com/Brewtarget/brewtarget/pull/498 for this.

**Comment by matty0ung** [comment]
Closing as I believe the 3.0.0 release should have improved logging for diagnosing this sort of issue.  But please reopen if you are still having similar problems with the latest version of the software.
