### ISSUE TITLE
2.4 Verson

### ISSUE THREAD

**Issue by Dieter-W** [Brewtarget/brewtarget#481]
Do you have any plans to provide a 2.4 version on the brewtarget webside?

I run a windows machine and was not able to build the current version on my PC, so it would be nice you provide an update on the webside

**Comment by mattiasmaahl** [comment]
While I cannot tell you exactly when 2.4.0 will be released, I can tell you we're working on it.

I just sent a PR to fix the stable/2.4.0 so it builds on windows if that gets merged you can build that branch on windows.
Otherwise I may be able to help you get an installer to run.

**Comment by Dieter-W** [comment]
Thanks Mattias,
I let you know how it works out

**Comment by beren12** [comment]
Any chance of rolling a release soon? I know there's some db work going on but it's been 5 years or so. And please let it work on older os x, 10.12/13 at least.

**Comment by matty0ung** [comment]
This is a decision for @mikfire, since he's de facto owner of the project.

Seems like a 2.4.0 code branch exists so it would probably be relatively small work to get a 2.4 release up here on github, depending on what additional things, if any, we want to merge in from master.  (Thanks to work by @xzfantom and @mattiasmaahl we can now do all the compilation on github VMs, so we're no longer blocked by none of the currently active developers having a Mac, which was a bit of an issue before.)

I'm not sure about the brewtarget website though.  We'd need to find whether anyone has the log-ins.  I seem to recall @mikfire saying he does not, or at least does not have them readily to hand.  (I emailed @rocketman768 about this a few months ago, but he didn't get back to me, so I'm not sure if he doesn't have the log-ins any more either or was just a bit busy at the time.)

**Comment by beren12** [comment]
So I built the 2.4 branch with qt-mac from fink, but it didn't copy the libraries to be where they need to be. not sure what to do next

**Comment by beren12** [comment]
I was able to get the 2.4 branch built and not crashing. The Mac doesn't need make package, the .app and the .dmg are built with make. My issue was 2 things: fink used .so for the qt platform libraries, and not all of them got copied (which is noted in the Mac docs)

I tried to build the latest dev branch but I need to install a newer Qt.

One thing I saw was the buildbot is requiring 10.15 or later for the OS X version, but that can be adjusted in the cmake makefile. I'd love to see 10.9 compat but at least bring it back to 10.13 please. Many users aren't running the latest OS X because of removed features/older hardware.

**Comment by matty0ung** [comment]
If you can put together a PR that makes things better on the Mac then that would be very welcome.

It's tricky to get the right balance with versions.  We'd like to support people running older OSs, and at the same time we rely on recent versions of libraries and frameworks for a lot of functionality.  Sometimes we can, eg, use an older version of Qt with a small workaround, so it's worth investigating if you have suitable machines to build on.

**Comment by matty0ung** [comment]
Version 3.0.0 is now live, so I'm closing this ticket.

We do not, unfortunately, have a way to update the brewtarget.org website as none of the current maintainers have access to it.  Current releases are all on github.
