### ISSUE TITLE
Default SQLite database file: hop, fermentable, mashstep, misc and yeast tables have unused columns

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#557]
AFAICT the `display_unit` and `display_scale` columns on the `hop`, `fermentable`, `mashstep`, `misc` and `yeast` tables in `default_db.sqlite` are not referenced anywhere in the code and could be removed. (On `mashstep`, there is also `display_temp_unit`, which falls into the same category.)

**Comment by xzfantom** [comment]
I was thinking about this idea of using db dump for initialization. As soon as we have good xml system now - isn't it better to use beerxml files for it? So our database would be independent from data we load to it. After introducing BeerJSON we could switch on that format. This way we don't need to worry about initial data and database tables.

**Comment by mikfire** [comment]
First. Eeep! Those are still in there? Sweet mercy. The original idea was to allow each individual row to have its own display units and scale. I could never make it make sense to anybody including me, and so was dropped. I think I just recently removed many of the commented out bits of code. Yes. Those columns need to be dropped.

SQLite is the native data format for brewtarget. I would prefer to ship our data in our format, rather than ship our data in a non-native format and then have to translate the data into the native format. When the non-native format is beerxml, it makes my preference even stronger.

**Comment by xzfantom** [comment]
> SQLite is the native data format for brewtarget. I would prefer to ship our data in our format, rather than ship our data in a non-native format and then have to translate the data into the native format. When the non-native format is beerxml, it makes my preference even stronger.

I've got your point and mostly agree. And there is no real important problem we solve if change shipping format now. And looks like BeerXML is not the best solution. I'd get back to this discussion after introducing BeerJSON. The profits of using non-native format, as for me, are:

- we don't need to care about changes in data if we change table scheme
- data is stored in human-readable format
- in future can package different data for different regions (may be in different languages)
- support different backends (SQLite or PostgreSQL)

Minus is a little longer first start, but it happens only once (or with every update), that is not so often.

**Comment by matty0ung** [comment]
I am going to do this as part of the BeerJSON work.  We're doing a ton of other updates to the database, so we might as well clean up these old columns at the same time.

**Comment by matty0ung** [comment]
This is fixed as part of the BeerJSON work.
