### ISSUE TITLE
Beer XML imports don't seem to be working.

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#576]
If you export a recipe to XML and then try to import it, brewtarget will crash on inserting the fermentables. If you enable the debug output, you will be told that there is a constraint violation when inserting a new fermentable_child row.

Is this expected to be broken right now or not?

**Comment by matty0ung** [comment]
Hmm, interesting, I get the same error:

```
The application encountered a fatal error.
Error message:
INSERT INTO fermentable_children (parent_id, child_id) VALUES (:parent, :child) UNIQUE constraint failed: fermentable_children.child_id Unable to fetch row.

```

I'll have a further look.

**Comment by mikfire** [comment]
Thanks. I poked at the XML import code for a while, but couldn't understand it well enough to figure out the problem.

The easiest way I could see to get that error message is if you are literally trying to add the same child ingredient twice. The easiest way to make that happen would be to throw the noCopy flag on the call to Database::addNamedEntityToRecipe() after having already added the named entity to a recipe.

**Comment by mikfire** [comment]
There is something wrong with either the default database or the default recipes.

I've found one issue with the children tables not being populated properly. I have a fix and will submit the pr later.

Fixing that doesn't fix the import problem. 

If I try to import the recipe into my postgresql database, it at least doesn't dump core. None of the quantities are imported, and we've a date string somewhere that is not making postgresql happy. I will chase that down later.

This suggests to me that we've a few issues here. The failing insert is something related to the data in the default database. And there's still an issue with the export/import not loading correctly.

**Comment by matty0ung** [comment]
Thanks for the extra diagnostics, that's useful stuff.

I think the import code is saying "Ah, I have this fermentable already, so I can skip over it on the import" but then, when it gets to the recipe it (a) doesn't spot it's a duplicate (ie something we just exported) and (b) is missing the crucial logic of "make a copy of something when you add it to the recipe and add the copy instead of the thing you were going to add".  My instinct is to fix (b) by adding that latter logic to the Recipe::add<T>() function(s), but if that starts looking too knarly, I'll do it in XmlRecipeRecord::addChildren().  Fixing (a) is a nice-to-have but, again, I'll see if "comparing two recipes for equality" is going to be more hassle than it's worth.

For the postgresql stuff, I'm a bit more puzzled, as the BeerXML import doesn't talk directly to the DB.  Instead, it asks each object it's read in (eg Fermentable, Hop, etc) to store itself in the DB, by calling the virtual member function `insertInDatabase()` which, in turn, calls the relevant member function of the `Database` class.  Am I right in thinking that the differences between SQLite and PostgreSQL are only exposed inside Database (and its related classes such as TableSchema etc) and the rest of the code generally doesn't need to know about them?  Or is there some extra step/check that I might be missing?

**Comment by mikfire** [comment]
The other issue is, I suspect, the result of how we store things like hop.type and hop.form in the database. The more I think about it, the more I am certain I know this is the problem. I had issues just like this previously. I just need to figure out where the code is.

I am really close to done with that issue and reworking things to only store the enumerated type in the database.

**Comment by mikfire** [comment]
Ok. I think I can move this along. Any place using allPropertyNames() is probably wrong. With some search/replace in beerxml, I've at least got the categories importing correctly.

The amounts still seem a little hit or miss (two of the fermentables showed 0g), and the mash infusion temperatures are still showing 0C.

**Comment by mikfire** [comment]
Ok. I got the final couple of issues. There was a missing field definition in beerxml for infuseTemp_c. This was causing it to not be read (I think) from the XML file, so there was nothing there to store.

I also had to disable the duplicate protections for mashes and I disabled the unique name requirement too. I am dead positive the first one is required. Mashes don't work quite like ingredients and you can't really have a "duplicate". I am not as certain about the second one. But just because my buddy called his mash "MyMash" doesn't mean it is the same as the mash I have called "MyMash" and we should just import it.

Now import/export seems to be behaving.
