### ISSUE TITLE
Brewtarget  (2.4.0) crashes when copying recipe

### ISSUE THREAD

**Issue by Alge** [Brewtarget/brewtarget#589]
Steps to reproduce:

1. create a new empty recipe
2. right-click -> copy
3. brewtarget crashes

I used the .deb from the latest build (from today, 2021-05-11)

**Comment by mattiasmaahl** [comment]
Yes, Saw that too, but I think it is fixed in PR #586 if I'm not mistaken. I'll test and see.
You can try that PR yourself with this link: https://github.com/Brewtarget/brewtarget/suites/2706872450/artifacts/59667203

**Comment by Alge** [comment]
Tried, and it still crashes

**Comment by mattiasmaahl** [comment]
I have found that when you try to copy a recipe without a MASH defined the crash happens. Can you confirm that this is your case?
I'll try to figure out a fix, maybe one of the Database-gurus, @mikfire or @matty0ung can fix it faster, meanwhile I'll look into it though.

**Comment by matty0ung** [comment]
Had a quick look.  Database::newRecipe(Recipe*) calls Database::addToRecipe(Recipe*, Mash*, bool, bool) which then calls template<class T> T* Database::copy( NamedEntity const* object, QHash<int,T*>* keyHash, bool displayed = true ) which probably barfs when trying to invoke object->metaObject()->className() on object = nullptr.

The short-term fix is to put in nullptr checks on copy() and/or addToRecipe(), as you see in multiple other places in the code. @mattiasmaahl You could do this safely I think if you have time.

Longer-term, I have this crazy idea about doing more in the object model and less direct action with the database.  (Eg, instead of asking the database to create/copy objects, we would ask the objects to do that, and then just save the new objects to the database.)  If I ever get it working in Brewken then I'll share the code an you can see what you think, but it might be a few months off. :)

**Comment by mattiasmaahl** [comment]
I noticed the that there is no null-checking there and was thinking about doing that as a fix also.

I'll code up a fix tomorrow for this if that's OK. Today, of all days, I had work to do, AT work! Can you believe it! 😂
Hopefully I'll have the PR ready tomorrow afternoon if AGW.

**Comment by mattiasmaahl** [comment]
so found a few minutes this afternoon to do the quick-fix null-checking. PR up for review (#590)
