### ISSUE TITLE
Real time search feature

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#6]
From [launchpad](https://bugs.launchpad.net/brewtarget/+bug/1424161)

It would be very handy if the ingredient list windows had some sort of search field, allowing us to search for some text string, and having the list view update to show only the matching items.
For example, I could then type "cara" in the search field and it would show me also items named like "Simpsons - Caramalt".

**Comment by dpettersson** [comment]
Should the searchfield be a permanent textfield or a popup?
Which is the preferred style?

**Comment by theophae** [comment]
I found why the row size change. It is because of this line
tableWidget->verticalHeader()->setDefaultSectionSize(20);
By the way, I do prefer when the lines are thinner, so it would be better change their default height, but this is my opinion.

**Comment by dpettersson** [comment]
That line "fixed" the problem. The problem was this:
When the filter was applied some of the lines became 2 rows (instead of 1). It changed back when i changed the search phrase. 
I tested to find the same height as the other windows and 20 seemed to be the correct number. I also  searched for how to set the height and the solution i used was the one i found. I will change it if you can point me at the correct function. :)  I am fairly new to Qt-development so i appreciate all comments and tips that i get. :)

**Comment by theophae** [comment]
I got the problem by searshing something that give not result then I erased the filter field and I got thinner lines.
I don't work on Brewtarget for very long time too, so I can help you that much.

**Comment by theophae** [comment]
About the size of the lines, I think it would be better to set it like this:
```C++
parentTableWidget->verticalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
```
in 
```C++
FermentableTableModel::FermentableTableModel(QTableView* parent, bool editable)
```
This will handle the line height for all table occurrences (dialog & fermentable tab)

You should also remove all the occurrences of
```C++
parentTableWidget->resizeRowsToContents();
```
In my view, they become useless.
