### ISSUE TITLE
Final Batch Sparge always assuming 15min in Mash Wizard

### ISSUE THREAD

**Issue by renato** [Brewtarget/brewtarget#63]
I created a mash configuration that has a "Final Batch Sparge" of 20 min. It is not a big deal, but even if I have a "Final Batch Sparce" with this duration, the wizard always assumes 15 min:
https://github.com/Brewtarget/brewtarget/blob/master/src/MashWizard.cpp#L291

Another point that is not a big deal but sounded strange to me is that I changed the name "Final Batch Sparge" to "Fly sparge" (which is what I do) and the Mash Wizard ended up creating the step again:
https://github.com/Brewtarget/brewtarget/blob/master/src/MashWizard.cpp#L251

I think that it'd be interesting to set a mash step as the sparge step (a new checkbox or new infusion type) so the Mash Wizard wouldn't need to compare the step name with a hardcoded string.

Plus, if a mash step for sparge is already present, its time should be used instead.

**Comment by theophae** [comment]
I also think that to add a checkbox to indicate the sparge step could be a good idea.

**Comment by dpettersson** [comment]
I feel that a little more information is needed in order to be able to implement this.

The hardcoded value of 15 minutes is a simple thing to change. The name is also simple, but it raises a question if we need to be able to handle more languages (the name of the sparge is hardcoded and thus only suports English). The idea about the checkbox could solve the name problem, but can the function be used for anything other then batch sparging?  It looks like the wizard recalculates (all?) the needed volumes when used.

**Comment by dkoppenh** [comment]
Also, please consider the case for no-sparge / BIAB.  A checkbox y/n would help with that.

**Comment by dpettersson** [comment]
It feels like there is a need to extend the wizard with som options.

**Comment by rocketman768** [comment]
Yeah, there needs to be a total rework of the mash wiz into a real wizard dialog with options. Sparge, no-sparge, BIAB, internationalization, etc. need to be included.

**Comment by theophae** [comment]
Wouldn't it be a good idea to add "Sparge" to the mash type in addition to "Infustion" "Temperature" and "Decoction"  ?
This won't replace all the work on the mash wizard, it is just another option than adding a checkBox.

**Comment by mikfire** [comment]
If you want, I have a branch called feature/newmashtype with 90% of the
work done. It has the code for two new sparge types: flySparge and
batchSparge. There is, as far as I can tell, just one outstanding bug that
I was never able to squash.

The issue that I cannot resolve is when using the mash designer. If you
create (for example) two sparge steps at the end and then close the mash
designer, the last sparge step gets way too much volume. In fact, the
earlier sparge steps are ignored and the last sparge gets the volume you
would expect if it were the only sparge step.

I have spent weeks trying to figure out what is doing that and I have never
been able to find the code that makes that happen. I eventually gave up.

There are some other ... issues. For example. If the user wants to raise
the temperature of the mash to 170F and we are doing a double batch sparge,
what temperatures do we specify for the sparge water? Assume we are doing a
total of 16L sparge (pretty typical for me), and splitting the sparge into
8L each. If we want to raise the bed to 170F on the first sparge, the water
has to be near boiling; and the second sparge has to be at 170F.

I think, in that case, we need to treat it as a two-step infusion but that
gets even harder, since every new sparge step requires us to adjust every
previous mash step.

Mik



On Mon, Sep 21, 2015 at 7:45 AM, theophae <notifications@github.com> wrote:

> Wouldn't it be a good idea to add "Sparge" to the mash type in addition to
> "Infustion" "Temperature" and "Decoction" ?
> This won't replace all the work on the mash wizard, it is just another
> option than adding a checkBox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/63#issuecomment-141949723>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by rocketman768** [comment]
That would be sweet. Put it up and we can take a look and have detailed discussions in the merge request.

**Comment by mikfire** [comment]
Sorry, I don't quite know how to link to a branch in github. You can see it
here: https://github.com/mikfire/brewtarget/tree/feature/newmashtype

and it is a fair way behind master. I can do a merge and what not, but it
shouldn't matter with respect to the issues I was having.

It does make changes to the database, so you will want to backup of the db
or (better) run this in a vm. As I recall, I had it almost all working
except for the oddity I mentioned.

Mik

On Wed, Sep 23, 2015 at 1:14 AM, Philip Lee <notifications@github.com>
wrote:

> That would be sweet. Put it up and we can take a look and have detailed
> discussions in the merge request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/63#issuecomment-142494085>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by mikfire** [comment]
I think this has been largely resolved with the new mash types. I am going to close this request
