### ISSUE TITLE
[Feature Request] : Add alcohol tolerance as optional parameter in yeast database model and manufacturer's link ?

### ISSUE THREAD

**Issue by bebenlebricolo** [Brewtarget/brewtarget#639]
Hi folks  !

I've been poking around several times in Brewtarget and I've added several yeasts that were not present in the database yet.
And I've noticed there is nowhere we can specify the maximum alcohol tolerance nor giving the link of the manufacturer's host page for the yeast, except from the Notes area where we can indeed specify it.

Do you think that's a good idea to add the alcohol tolerance ?
At least to me, that's a good point when you try to design strong ales such as imperial stouts where you're pushing yeasts to their very limits ; alcohol tolerance is (one of) the main factor(s) that limits the final product's overall alcoholic content !

Another question which is related to this one (more or less) : I saw brewtarget uses sqlite to handle data storage ; is it possible for us, as end user, to contribute to its default population ?
I mean much like what FreeCAD community does with the external FreeCAD-Library project, where external contributors can enrich the existing data repository.
[ This question itself can also become another "issue" ticket, sorry for packing both in the same place :smile: ]

**Comment by matty0ung** [comment]
Hi!

Personally, I'd say "Yes" to both questions. :smile: 

Alcohol tolerance is a defined field for "microbial cultures" in BeerJSON, so it's likely something we'd have been getting around to adding sooner or later as part of our long journey towards BeerJSON support.

Default data is actually slightly related.  We currently have a bit in SQLite and a bit in BeerXML.  Long-term we'd like to have it all in BeerJSON, because that's easier to version control than SQLite and more comprehensive than BeerXML.  Short-term, if you've got data in BeerXML that you want to upload here, that would be great.  We'll find a way to pull it into the install.

**Comment by bebenlebricolo** [comment]
Sure! I'm really glad to do be able to contribute like this as well ! :smile: 

I've packaged what I currently have at hands with those new yeasts.
[Lallemand yeasts.zip](https://github.com/Brewtarget/brewtarget/files/8102794/Lallemand.yeasts.zip)

In the future we can even imagine to sort yeasts by style, and even tags, that'll be really nice !
Many thanks for the reactivity, 2nd time opening an issue here for me and I had an excellent feedback from you guys, that's really motivating.

**Comment by matty0ung** [comment]
Cool.  We'll do a patch to add your extra yeasts in.

Don't worry if there's radio silence for a while. Sometimes takes a while for fixes to reach the front of the to-do list (eg am currently working on https://github.com/Brewtarget/brewtarget/issues/622) but we do try to get to everything!

**Comment by bebenlebricolo** [comment]
No worries, it takes time !
By the way, I browsed throughout the website (brewtarget.org) and did not find roadmaps, do you have any? Or do you use the issues tab as the main source for feature requests/bug tickets and so on?

I'm curious as I'm a C++ software developer as well and I'd be glad to give some help in the future (when I'll have advanced my other projects enough to spare some time again). Or maybe there is some kind of developer's discord channel or other discussion threads ?

**Comment by matty0ung** [comment]
Ah, hmm, yes, the website.  See discussion in https://github.com/Brewtarget/brewtarget/issues/493 but I think none of the active developers has access to update it, which is why it is very out of date, including with some duff/misleading links.  AFAIK pretty much all current discussion & planning happens here on Github.  Probably we could do more planning... :smiley:

**Comment by matty0ung** [comment]
This will be fixed in Brewtarget 4.0 which just putting together the release for.  All the Lallemand yeasts you uploaded (and more!) are now in the database and alcohol tolerance is now a supported field in the yeast editor (on the "Extras" tab).
