### ISSUE TITLE
Release 3.0.1 is uninstallable on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by jawsdaws** [Brewtarget/brewtarget#665]
Trying to install 3.0.1 on Ubuntu 22.04.1 using the release deb gives and error `brewtarget : Depends: libxalan-c111 but it is not installable`  . The version of Xalan in the 22.04.1 repo is libxalan-c112.  Was 3.0.1 built on/for 20.04 by chance?  That would match with libxalan-c111.

**Comment by matty0ung** [comment]
Ah, hmm, that's interesting.  The builds are all done on Github VMs (via Github Actions).  The Debian packages are created on an "ubuntu-latest" VM, so I would have thought that would be 22.04.  I'll investigate further...

**Comment by jawsdaws** [comment]
A little digging shows it is indeed built on focal 20.04. Not exactly "latest" :-)
![Screenshot from 2022-10-16 08-11-30](https://user-images.githubusercontent.com/3501812/196034782-fc7522a4-23aa-48d6-b614-7c0051b1d203.png)

**Comment by penguinpee** [comment]
Could someone edit the title of this issue, please? There's no 3.01 release.

**Comment by jawsdaws** [comment]
> Could someone edit the title of this issue, please? There's no 3.01 release.

Done.

**Comment by matty0ung** [comment]
So, it seems this is to be expected until "the near future" whenever that is (see https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/).  Maybe we should just manually specify 22-04 and remember to update it in two years' time. :smile:

**Comment by jawsdaws** [comment]
I'm not familiar with how big a pain it is to change this, but targeting latest LTS seems like the best option.  Will "latest" refer to non-LTS releases in the future?  I'm not sure you would want that...

**Comment by matty0ung** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, "The -latest runner images are the latest stable images that GitHub provides, and might not be the most recent version of the operating system available from the operating system vendor."  So, I would generally expect them to be a recent LTS for Ubuntu.

That said, it's actually not a huge deal for us to manage this directly.  Unless there's something else I'm forgetting, we just change line 19 of https://github.com/Brewtarget/brewtarget/blob/develop/.github/workflows/linux-ubuntu.yml.  (I know the code builds OK on 22.04 because that's what I'm running locally!)

I will try to get to this soon, unless someone else wants to jump in first with a PR.

**Comment by matty0ung** [comment]
OK, I've done a build on Ubuntu 22.04 and uploaded the packages from that at https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.1  (You'll need the `brewtarget_3.0.1-2_amd64.deb` file rather than the `brewtarget_3.0.1-1_amd64.deb` one.)  Let us know how you get on.

**Comment by matty0ung** [comment]
Closing this as https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.2 now available.  As ever, please let us know if you hit problems.
