### ISSUE TITLE
"Copy Recipe" doesn't input inventory quantities

### ISSUE THREAD

**Issue by eyousey** [Brewtarget/brewtarget#72]
When you copy a recipe, it doesn't update the inventory columns of the new recipe. I shows "zero" as being in your inventory. Items have to be re-added to the recipe for the inventory columns in the recipe to be update.

BrewTarget 2.1.0
FreeBSD 10.1 (64bit)

**Comment by rocketman768** [comment]
Like something underneath [Database::newRecipe(Recipe*)](https://github.com/Brewtarget/brewtarget/blob/master/src/database.cpp#L1160) is not updating the inventory tables for the copied ingredients.

**Comment by theophae** [comment]
This seems not to be a bug. The problem is that when you copy a recipe it does the same as if you import a recipe from a beerXML file. I mean all the ingredients are copied for the recipe only.
To me, the problem is bigger than this, we must consider using ingredients without making a local copy for the recipe.
To me, it is not easy to manage an inventory by doing like this. I've personally never used this functionality because it doesn't work for imported (and copied) recipes.
So I don't know if this bug worth spending time on it...

**Comment by mordante** [comment]
I'm still not really familiar with the database structure, but I think the issue stems from setting the ingredient's parent (in $ingredient_children table) to the ingredient's ID instead of the base ID. When the ID is set to the ingredient's grand parent things seem to work.

Attached a proposed fix. If this seems the proper solution I'll make a pull request.
[patch.txt](https://github.com/Brewtarget/brewtarget/files/478864/patch.txt)

[Uploading patch.txt…]()

**Comment by mikfire** [comment]
Closed with merge commit 4c9f766
