### ISSUE TITLE
Two Running Brewtargets Resets Database

### ISSUE THREAD

**Issue by eyousey** [Brewtarget/brewtarget#73]
I see there is a previous bug for this (#1109597) on lauchpad, but it is still happening.

I accidentally ran two versions (back-to-back) and now my database was reset back to the default. It seems you put in a lock file, but maybe in my case they both launched before the lock file was created.

I did not alter any recipe info when I had both (accidentally) open, I was just viewing. When asked to save my changes, I said, "No."

This being KDE 4.14.3 on FreeBSD 10.1 (64bit) I closed the "<2>" version first.

Can a check be added to only allow one client to connect to the database at once?

As a an additional level of safety, make a backup copy of the database at each launch and shutdown with a unique time stamp appended to the file name. Keeping maybe 10 or so backups in rotation. Potentially have this number of backups as a user adjustable number.

Thanks.

**Comment by rocketman768** [comment]
Race condition between [brewtarget.cpp:478](https://github.com/Brewtarget/brewtarget/blob/master/src/brewtarget.cpp#L478) and [brewtarget.cpp:486](https://github.com/Brewtarget/brewtarget/blob/master/src/brewtarget.cpp#L486).

Desired fix is to replace the pid file logic with [QSharedMemory](http://doc.qt.io/qt-5/qsharedmemory.html) communication.

**Comment by malavv** [comment]
Thanks @rocketman768 for finding the source of the issue.

**Considerations**
* It seems that whatever the fix is needs to be multi-platform.
* The two only things that are shared by application instance are Settings and Database.
* QSetting is reentrant and can be accessed by multiple instances.
* At this point, all instances will be running the same DB (due to user-data-dir in settings), but it might not be the case soon.

**Conclusion**
* Could we check for multiple access to the same DB instead? Since this is were the problems will come from?

**Comment by mikfire** [comment]
This will be fixed soon. I've got a branch that seems to get the work done https://github.com/mikfire/brewtarget/tree/bugs/twobt but I need to work on it a bit more.

**Comment by mikfire** [comment]
Clsoed with merge request #260
