### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by adjunkth** [Brewtarget/brewtarget#764]
Is it possible to donate to this project?

The github readme states that the old brewtarget.org is no longer maintained. Is the link to donate on that page still correct?

**Comment by matty0ung** [comment]
That's a kind offer.  I'll find out the best way to make it possible.  (I think we can set up a way to do it via github, but I need to check the details.)

The details on the old brewtarget.org site are out indeed of date.  (Unfortunately, nobody seems to have the admin credentials for the site, so we can't update it!  Maybe we just need to register a new domain name.)

**Comment by matty0ung** [comment]
OK, so here are the long and the short answers.

Short Answer: This is the current link for donations: https://github.com/sponsors/matty0ung

Long Answer: Unlike some of the bigger open source projects, there is not separate "entity" behind Brewtarget.  The project exists because of the combined efforts of a number of developers who have come and gone over the years.  Any donations would go to an individual developer.  I'm currently the lead developer and main contributor, so the link above is for me.   The old link on the brewtarget.org website sends money to the original developer, Philip Lee, who was active on the project from 2009-2015 and wrote a lot of the original code, but he then moved on to other things and hasn't been involved for some time.  He passed the torch to Mik Firestone, who contributed since the early days and, over the years, created a lot of the features in the current product.  In recent years, Mik has dialled back his involvement, and he handed over the helm before the last major release.

I've been working on the project since 2020.  I've added a few features (eg Undo/Redo, radar charts, improved ABV calculations) and have spent a lot of time improving the inner workings of the product (new build & packaging system, more robust BeerXML processing, new database layer, improved & extended weights-and-measures system).  I'm currently working on BeerJSON support which is a pretty big change to the software.  Amongst other things it adds lots of new fields and fixes some of the design problems that we inherited from the original BeerXML specification.  It will also allow us to have a much updated and expanded database of hops, fermentables, styles and so on.

**Comment by matty0ung** [comment]
Thanks for the donation! :bow: :+1:

**Comment by penguinpee** [comment]
How about donations in natura? I know writing code is a thirsty business. :stuck_out_tongue_winking_eye: :beers:

**Comment by adjunkth** [comment]
Thank you for all your work

Matt Young ***@***.***> skrev: (24 juli 2023 18:41:58 CEST)
