### ISSUE TITLE
Hop editor layout broken

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#8]
From [launchpad](https://bugs.launchpad.net/brewtarget/+bug/1409329)

Not sure if this still applies. There is no top-layer layout in the Hop Editor, so re-sizing the window does not move the widgets.

**Comment by theophae** [comment]
Do anyone see this bug ?
To me it is no more applicable.

**Comment by mikro2nd** [comment]
Not sure that this is the same thing, but the bug seems valid to me. Steps to reproduce (in 2.1.0):

1. Open the hop editor. (As luck would have it the hop I chose has a name too long to fit in the default width Name field.)
2. Resize the editor (drag right-hand border wider).
All labels and fields remain the same width; only some blank area opens up to the right of the existing labels and widgets.

**Comment by theophae** [comment]
I did these manipulation on 2.1.0 and on the current version, and in the second case the problem does not appear. It seams that it has been already fixed.

**Comment by mikro2nd** [comment]
Nope - still a bug in 2.1.0. Widgets do not stretch/shrink as the surrounding popup window is resized. Screenshots attached to try and make clear what I'm getting at.

Default hop editor popup (Double-click on a hop variety to edit the hop details.):
![hopeditor-default](https://cloud.githubusercontent.com/assets/310455/10262156/0c8925e2-69bc-11e5-9d81-beb3fdc6512f.png)

Oops, the "Name" field is too narrow to show all of Columbus/Tomahawk/Zeus, so stretch it wider:
![hopeditor-wide](https://cloud.githubusercontent.com/assets/310455/10262160/2d19df90-69bc-11e5-94a7-6dc84dae958b.png)

Well, that didn't work as I'd expect. Try making it narrower:
![hopeditor-narrow](https://cloud.githubusercontent.com/assets/310455/10262163/403cd852-69bc-11e5-867b-4c68dcdf7011.png)

See what I mean? ;)
