### ISSUE TITLE
Crash editing Target Boil Size

### ISSUE THREAD

**Issue by anthonykelly** [Brewtarget/brewtarget#817]
Full Log: [brewtarget.log](https://github.com/user-attachments/files/16834690/brewtarget.log)

I  am finding Brewrarget 4.0.3 crashes more often in various situations. This one seems to be fully repeatable for me on Ubuntu and MacOS.

Edit a recipe and change the "Target Boil Size". 
`[09:24:31.290] (1bf3iy2n0g) ERROR : ASSERT: "!this->getTypeInfo().isOptional()" in file ../src/widgets/SmartField.cpp, line 388  [widgets/SmartField.cpp:388]`

**Comment by matty0ung** [comment]
Thanks for the log file and info.  I will have a look this evening.  One of the changes in 4.0 is that a lot of numerical fields are now optional (ie blank is allowed) where, previously, if there was no available or meaningful value, you had to put 0.  The assert is saying that the UI is trying to treat something as optional when it is not.  Will likely be a quick fix.

**Comment by anthonykelly** [comment]
Another example of a crash I'm seeing is editing the Mash Amount
`[15:19:50.013] (3tdwh1c) ERROR : ASSERT: "!physicalQuantity" in file /Users/akelly/brewtarget/src/tableModels/TableModelBase.h, line 730  [tableModels/TableModelBase.h:730]`

**Comment by matty0ung** [comment]
Thanks for the extra log message.

About to commit small fixes for both of these.  Please keep letting me know about other issues you hit.

**Comment by matty0ung** [comment]
Just to give you a bit more background, another change in 4.0 is that I tried to further reduce the amount of copy-and-paste code between similar bits of the program.  Eg the grids at the bottom of the recipe to list fermentables, hops, mash steps, etc are all super similar.  Since we were adding new tabs there (Boil and Fermentation), I wanted to pull out as much common code as possible.  In the long run, this will mean more consistent behaviour and fewer bugs (honest!).

We are not 100% where I want to be yet -- eg you can see that some fields still blank their contents when you double-click to edit them because the "what should we show during edit" logic is not yet centralised.  But it's hopefully moving in the right direction.

**Comment by anthonykelly** [comment]
Thanks, Matt, I rebuilt from latest and those two issues seem to be resolved.

However, editing the Boil Step Name in the Boil Step Editor produced another crash...

`[09:18:29.092] (3tdwh1c) ERROR : ASSERT: "!this->getTypeInfo().isOptional()" in file /Users/akelly/brewtarget/src/widgets/SmartField.cpp, line 390  [widgets/SmartField.cpp:390]`

Likewise editing Fermentation Step Name produces...
`[09:21:21.612] (3tdwh1c) ERROR : ASSERT: "!this->getTypeInfo().isOptional()" in file /Users/akelly/brewtarget/src/widgets/SmartField.cpp, line 390  [widgets/SmartField.cpp:390]`

So hopefully the same fix for both.

**Comment by matty0ung** [comment]
Yes, that's almost certainly the same sort of fix.  Will have a look after work.

**Comment by anthonykelly** [comment]
Thanks, @matty0ung , all of these crashes are fixed now. Tested on macOS and Ubuntu.

**Comment by matty0ung** [comment]
Fix included in [4.0.4](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.4).
