### ISSUE TITLE
Adding Mash Step causes core dump

### ISSUE THREAD

**Issue by JhPj4VOb2h** [Brewtarget/brewtarget#847]
Adding a mash step with the plus sign gives me a core dump. Ubuntu 22.04. Compiled brewtarget to get version 4.0.6. 
Opened the bt recipe Bt: American Barleywine. Everything looks like it is filled in correctly. Clicked on 'Mash' tab. Then clicked on blue plus sign. Program dies and prints out:

[21:00:12.172] (17vxqiaklc) INFO : void {anonymous}::finishCheckForNewVersion() Latest release is "4.0.5" (parsed as 4.0.5 ) ; currently running 4.0.6 (parsed as 4.0.6 )  [Application.cpp:255]
[21:00:43.567] (17vxqiaklc) ERROR : ASSERT: "!this->startTempIsRequired() || this->m_startTemp_c" in file /home/XXXX/Software/BrewTarget/brewtarget/src/model/Step.cpp, line 154  [model/Step.cpp:154]
Aborted (core dumped)

Same error if I create a new recipe and try to create a new mash step.

**Comment by matty0ung** [comment]
Sorry you're hitting problems.  I've had a quick look and I know what's causing this.  Will do a fix.

**Comment by matty0ung** [comment]
I have a fix for the core dump.  Just adding in a bit more wiring so that, after you click save, the Mash Step shows up in the Mash.  (The inner workings have changed very slightly because we now also need to be able to add a Boil Step to a Boil and add a Fermentation Step to a Fermentation.  It's all essentially the same idea, so the code is shared across all three.)

**Comment by JhPj4VOb2h** [comment]
Thanks. Glad to know it was a relatively easy fix. 

Now to find more bugs. 😉

⁣Mitch​

**Comment by matty0ung** [comment]
Fix included in [Release 4.0.6](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.6).
