### ISSUE TITLE
Crash on Windows when opening Print and Print Preview dialog

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#873]
Title describes the issue.  Log attached.  General question; do you want a separate issue filed for every individual, distinct issue or one covering several?  There are other issues I've encountered...
[brewtarget.log](https://github.com/user-attachments/files/17656131/brewtarget.log)

I don't know if it's related but there's a long "waiting for printer connection" dialog each time I start the program.

**Comment by matty0ung** [comment]
Sorry for the slow response.  Yes, please, if you can make a separate issue for each bug, that would be great.  If it turns out two bugs have the same cause, we can just merge the issues later.

I'm not able to reproduce this bug on my machine, and the log doesn't seem to have captured any info about it, so I might need a bit of help on the diagnostics.  Could you

- change your log settings (Tools > Options > Logging) to "Detailed (for debugging)"
- close the program
- delete all the `brewtarget*.log` files
- start the program
- reproduce the crash

Then attach all the log files to this ticket?  (There will likely be several log files because the program starts a new log file once an existing one gets to about 500KB in size.)

If you want, you could wait for the 4.0.10 release (coming in the next couple of days hopefully!).  I don't think it will address this bug, but it should fix some of the other ones you're seeing!

**Comment by karthil** [comment]
Thanks. I'll wait for the next release before filing anything else to avoid filing bugs already addressed in the latest.

**Comment by matty0ung** [comment]
The [4.0.10 release](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.10) is now available.

**Comment by karthil** [comment]
Confirmed the issue is reproducible with the latest version.  Log file attached with debug logging enabled and after a launch following deleting the old log files.  

I can submit the other issues (IBUs not updating, drop down boxes too narrow to see contents, OG only updating when adding or removing things like yeast, etc).  Or, if you'd prefer, I can try wiping my context if possible to see if that helps given you weren't seeing some of these issues.
[brewtarget.log](https://github.com/user-attachments/files/17786861/brewtarget.log)

**Comment by matty0ung** [comment]
Thanks.  I'll take a look.

And, yes, please do feel free to raise issues for other problems.

**Comment by matty0ung** [comment]
I've managed to reproduce this.  It happens on Windows but not on Linux.  Windows Event Viewer says `Exception code: 0xc00000fd` which is apparently stack overflow.  My first guess is we're creating something large on the stack that we ought instead to be creating on the heap, and we get away with it on Linux but not on Windows.  But I'll fire up the debugger and take a proper look.

**Comment by matty0ung** [comment]
After digging in deeper, it's nothing to do with large objects.  Inside the function that gets called when the window is displayed, we're calling a function to display the window which, on Windows, then causes the function we're already in to get called again resulting in an endless recursion (and thus stack overflow).  Strange that it works on Linux and on older versions of Qt but, in any case, the solution is a one-line fix.  PR incoming.

**Comment by matty0ung** [comment]
Fixed in [4.0.11](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.11).
