### ISSUE TITLE
QtMultimedia gstreamer link issue

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#9]
This is from [launchpad](https://bugs.launchpad.net/brewtarget/+bug/1407480)

I don't quite know how we can solve this except wait for Qt 5.6 to become common so that all the linking happens properly.

**Comment by theophae** [comment]
From what I've understood, the problem comes from the use of QtMultimedia and QtWebKit on the same time. As QtMultimedia seems to be uses only for playing sound in the timer window, I wonder about using another library like SDL_mixer to play the sounds instead of using QtMultimedia.
It could be a momentary solution while the Gstreamer dependency is broken.

I'm looking for solution to solve this problem as it is very blocking for developing under linux. I'm a bit desperate because I can't build on Debian sid since a few weeks because they are doing some mess with Qt packages because of a migration. Moreover, I try several distros base on ubuntu like Liunx mint and Kubuntu, and on these ones I can compile, but I cannot launch brewtarget because of this bug.
I'm very sad to say that the last OS on which one I'm able to develop is windows :(

**Comment by rocketman768** [comment]
I don't really want to pull in other multimedia libraries.

What if we just add a preprocessor define like DISABLE_MULTIMEDIA and conditionally compile out all the multimedia calls in TimerWidget if this is defined?

**Comment by theophae** [comment]
I'm OK with that, but it doesn't solve the problem. It only allows to launch the binary to work on the rest of the software, but the timer widget won't be able to play any sound.
Does it mean that you won't release the version 2.2.0 until QtMultimedia hasn't been updated ? Or do you want to release the 2.2.0 version with a restriction on linux (and mac ?) versions ?
My feeling is that Qt team won't update QtMultimedia because they aims to replace it by a full implementation of HTML5 onto QtWebKit. As we have no visibility on it, we must find a momentary solution.

But while thinking to a better fix, we must put a compile flag to be able to keep developing.

**Comment by rocketman768** [comment]
5.5.0 was released on 1 Jul. Is the fix in there?

**Comment by theophae** [comment]
Yes, but I don't know why they left Gstreamer 0.10 as default, the 1.0 can be activated by a compilation flag. The resolution of this bug depend on Linux distros maintainers, if they decide to compile QtMultimedia with gstreamer 1.0, the problem will be solved.
As brewtarget is not the only project to have this problem, we can except it to be solved in most of the Linux distros.
But while it is not ok, I'd like to be able to compile without QtMultimedia. I've have found how to pass a compilation flag to cmake yet.

**Comment by rocketman768** [comment]
When we used phonon, we provided an option to disable all the phonon functionality. Take a look at [the commit that removed phonon](https://github.com/Brewtarget/brewtarget/commit/487557bad68bd6bd1e636fb1f621640ea87ee916).

**Comment by JulianVolodia** [comment]
Since Qt 5.5 they recommend to use QtWebEngine against deprecated Qt WebKit.

Default GStreamer is still 0.10 (I think, for backward-comp.).

More info here: http://doc.qt.io/qt-5/whatsnew55.html

Is that helpful? I read that issue only briefly...

**Comment by rocketman768** [comment]
Yeah, thanks for the news. I guess everything still on 5.4 or lower is
screwed anyway you look at it.

**Comment by JulianVolodia** [comment]
Sorry, I misunderstood you @rocketman768 
> I guess everything still on 5.4 or lower is screwed anyway you look at it.

**Comment by JulianVolodia** [comment]
@rocketman768  what about this? Have you any thoughts how it needs to be done and could leave some tips here? Thanks.

**Comment by xzfantom** [comment]
If we decide to change minimal supported QT version as in issue #521 this problem can be closed, too.

**Comment by xzfantom** [comment]
I think we can close this issue as minimal QT is 5.9.5

**Comment by mattiasmaahl** [comment]
You are correct. closing.
